services:
  # Backend API Service
  - type: web
    name: innosthan-backend
    env: node
    region: oregon  # Change to your preferred region: oregon, frankfurt, singapore, sydney, mumbai
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free  # Change to 'starter' or 'standard' for production
    healthCheckPath: /api/health
    
    # Environment Variables
    # Note: Add these in Render Dashboard or via CLI
    # Required variables:
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add these in Render Dashboard:
      # - MONGODB_URI (from MongoDB Atlas)
      # - JWT_SECRET (generate with: openssl rand -base64 32)
      # - CLIENT_URL (your Vercel frontend URL)
      # Optional:
      # - OPENAI_API_KEY
      # - AWS_ACCESS_KEY_ID
      # - AWS_SECRET_ACCESS_KEY
      # - AWS_REGION
      # - AWS_S3_BUCKET
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build settings
    buildFilter:
      paths:
        - server/**
    
    # Custom headers for CORS
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: ${CLIENT_URL}
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization

