services:
  # Backend API Service
  - type: web
    name: innosthan-backend
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://innosthan.vercel.app,http://localhost:3000

